### ISSUE TITLE
Podman unshare `Error: please use unshare with rootless`

### ISSUE THREAD

**Issue by Igortorrente** [containers/ansible-podman-collections#529]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Following the instruction in the [documentation](https://github.com/containers/ansible-podman-collections/pull/455/files#diff-628ad9cab176f2b22c27386d21d0acc2a368fc9836ffb67a2a63828bddb7a7ffR95-R106) I tried the new podman unshare `become_method`, but it didn't worked for me.

It seems to be running `sudo podman unshare <cmd>` under the hood instead of `podman unshare <cmd>` for some reason.

**Steps to reproduce the issue:**

1. Create a task with podman unshare

2. Run it

3. Face the error message

**Describe the results you received:**

``` yaml
failed: [instance] (item=/home/vagrant/containers_cache/redis) => {"ansible_loop_var": "item", "changed": false, "item": "/home/vagrant/containers_cache/redis", "module_stderr": "", "module_stdout": "Error: please use unshare with rootless\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 125}
failed: [instance] (item=/home/vagrant/containers_config/redis/) => {"ansible_loop_var": "item", "changed": false, "item": "/home/vagrant/containers_config/redis/", "module_stderr": "", "module_stdout": "Error: please use unshare with rootless\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 125}
```

**Describe the results you expected:**

Success

**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

``` Console
$ ansible-galaxy collection list | grep containers.podman
containers.podman             1.9.4  
```

**Output of `ansible --version`:**

``` Console
$ ansible --version
ansible [core 2.13.5]
  config file = /home/igor/projects/cloud/Caedrium-Playbooks/ansible.cfg
  configured module search path = ['/home/igor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/igor/projects/cloud/python3_venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/igor/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/igor/projects/cloud/python3_venv/bin/ansible
  python version = 3.10.8 (main, Nov  4 2022, 09:21:25) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

**Output of `podman version`:**

``` Console
$ podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.15
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 4
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: instance
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.0-18-amd64
  linkmode: dynamic
  memFree: 5475975168
  memTotal: 6229622784
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 0
  swapTotal: 0
  uptime: 1m 57.04s
registries: {}
store:
  configFile: /home/vagrant/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/vagrant/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/vagrant/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.15
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

``` Console
$ apt list podman
Listing... Done
podman/stable,now 3.0.1+dfsg1-3+deb11u1 amd64 [installed]
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
- name: Create all redis folders.
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 104
    group: 104
    state: directory
    mode: 0700
  become_method: containers.podman.podman_unshare
  become: true
  loop:
    - "{{ cache_dir }}/redis"
    - "{{ config_dir }}/redis/"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 11 running inside of Vagrant-libvirt VM.

**Comment by sshnaidm** [comment]
@grzs can you take a look?

**Comment by sshnaidm** [comment]
@Igortorrente did you try to put `become_user: <your_user>`  in the task?

**Comment by grzs** [comment]
yes, I will check it out. It should use sudo only if become_user has been set. If not, it tries to change the user namespace of the ansible_user. Do you connect as root? Or it is also possible that the become_user variable has a value set in the inventory, or earlier in the play.

**Comment by grzs** [comment]
@sshnaidm I've got it. It's not possible to use podman unshare as root because it doesn't make sense. How should we handle it? Simply bypassing it or throwing an error, or extending the documentation?

**Comment by grzs** [comment]
> @Igortorrente did you try to put `become_user: <your_user>` in the task?

This should work.

**Comment by sshnaidm** [comment]
> @sshnaidm I've got it. It's not possible to use podman unshare as root because it doesn't make sense. How should we handle it? Simply bypassing it or throwing an error, or extending the documentation?

Right now `root` is the default in https://github.com/containers/ansible-podman-collections/blob/73af4896b4994f68cd0c4d192ac148d09e4b0c9b/plugins/become/podman_unshare.py#L19-L21
Maybe worth to remove the default or use current/empty user as its default here? https://github.com/containers/ansible-podman-collections/blob/73af4896b4994f68cd0c4d192ac148d09e4b0c9b/plugins/become/podman_unshare.py#L133

**Comment by grzs** [comment]
oops... for sure, the default has to be anything but root (or no default). I am experimenting with it and creating a PR soon.

**Comment by Igortorrente** [comment]
> @Igortorrente did you try to put `become_user: <your_user>` in the task?

It works if I also remove the `owner/group` fields. Otherwise I get this new error:

``` yaml
failed: [instance] (item=/home/vagrant/containers_cache/redis) => {"ansible_loop_var": "item", "changed": false, "gid": 1000, "group": "vagrant", "item": "/home/vagrant/containers_cache/redis", "mode": "0755", "msg": "chown failed: [Errno 1] Operation not permitted: b'/home/vagrant/containers_cache/redis'", "owner": "vagrant", "path": "/home/vagrant/containers_cache/redis", "size": 4096, "state": "directory", "uid": 1000
```

**Comment by grzs** [comment]
@Igortorrente I suppose it's how podman unshare works. With podman unshare you can work with files in a specific user namespace, but it's not a permission elevation method from the host side, like sudo. It means that you still work as your unprivileged user, the only difference is that it maps user and group ids for you, like if you were in the container. Therefore the safe way is to use numeric ids instead of names, because names can be mapped to different numeric id on the host and in the container. With podman unshare (in rootless mode) you become the root user of the user namespace (and the container).
Let's assume that you have a container with a bind mount /home/vagrant/wd:/mnt/wd, and you want to set its owner to foo (uid 1000) in the container. Then you can do it by 'podman unshare chown 1000 /home/vagrant/wd' from the host by user vagrant. But it will fail if you try to do this with another user, who has no rights to change ownership of the above directory.
In your case it seems that the vagrant user is not permitted to change ownership of directory /home/vagrant/containers_cache/redis, and podman unshare is indifferent in that sense. 
I hope I understood your problem and could make it clear.

**Comment by Igortorrente** [comment]
Yeah, we have the exact same permissions as the the user that is running the podman unshare command.

What is strange is that vagrant user owns `{{ cache_dir }}` (and therefore have permission) and it should have permission(under podman unshare) to the redis folder as well. My understand about the `ansible.builtin.file` is that I'm running:

``` Console
(vagrant) $ podman unshare mkdir {{ cache_dir }}/redis
(vagrant) $ podman unshare chown 104:104 {{ cache_dir }}/redis
(vagrant) $ podman unshare chmod 0700 {{ cache_dir }}/redis
```

Which works (I tried here). But it doesn't works within ansible

**Comment by grzs** [comment]
> Yeah, we have the exact same permissions as the the user that is running the podman unshare command.
> 
> What is strange is that vagrant user owns `{{ cache_dir }}` (and therefore have permission) and it should have permission(under podman unshare) to the redis folder as well. My understand about the `ansible.builtin.file` is that I'm running:
> 
> ```
> (vagrant) $ podman unshare mkdir {{ cache_dir }}/redis
> (vagrant) $ podman unshare chown 104:104 {{ cache_dir }}/redis
> (vagrant) $ podman unshare chmod 0700 {{ cache_dir }}/redis
> ```
> 
> Which works (I tried here). But it doesn't work within ansible for some reason
@Igortorrente Can you paste the -vvv verbose output here?

**Comment by grzs** [comment]
@Igortorrente I tested it and encountered the same issue if group did not set correctly. Since you connected as root, all the files (and dirs) you create will belong to group 'root' by default. The problem is that from a mapped user namespace root is nobody:nogroup. The safest way if you connect as root is to set become_user at the play level, and set become_method to podman_unshare at the specific task where you need it.

**Comment by grzs** [comment]
Example playbook:
```yaml
---
- hosts: test_host
  become: yes
  become_user: vagrant
  vars:
    test_dir: "/home/vagrant/test"
  tasks:
  - name: creating a file
    ansible.builtin.file:
      state: touch
      path: "{{ test_dir }}/foo"
  - name: chown a file with unshare
    become_method: containers.podman.podman_unshare
    ansible.builtin.file:
      state: file
      path: "{{ test_dir }}/foo"
      owner: 1000
  - name: checking uid of file 'foo'
    ansible.builtin.file:
      state: file
      path: "{{ test_dir }}/foo"
    register: foo
  - ansible.builtin.debug:
      var: foo.uid
```
output:
```
TASK [creating a file] *********************************************************************************************************************************************************
changed: [test_host]

TASK [chown a file with unshare] ***********************************************************************************************************************************************
changed: [test_host]

TASK [checking uid of file 'foo'] **********************************************************************************************************************************************
ok: [test_host]

TASK [ansible.builtin.debug] ***************************************************************************************************************************************************
ok: [test_host] => {
    "foo.uid": "166535"
}
```

**Comment by grzs** [comment]
@sshnaidm here is the PR: #530 
I think if @Igortorrente agrees, you can close this issue.

**Comment by Igortorrente** [comment]
> @Igortorrente I tested it and encountered the same issue if group did not set correctly. Since you connected as root, all the files (and dirs) you create will belong to group 'root' by default. The problem is that from a mapped user namespace root is nobody:nogroup. The safest way if you connect as root is to set become_user at the play level, and set become_method to podman_unshare at the specific task where you need it.

One thing, didn't connect as root. I connect as vagrant, which is a regular user. 

It's in the `sudo` group, but it's not a privileged user. And I'm not using the sudo privilege in my redis task.

> @Igortorrente Can you paste the -vvv verbose output here?

``` Yaml
TASK [roles/containers/infra/redis/ : Create all redis folders.] ***************
task path: /home/john/projects/cloud/roles/containers/infra/redis/tasks/main.yml:6
<192.168.121.127> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.127> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.127 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
<192.168.121.127> (0, b'/home/vagrant\n', b'')
<192.168.121.127> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.127> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.127 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884 `" && echo ansible-tmp-1669856332.5616784-16360-75421636728884="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884 `" ) && sleep 0'"'"''
<192.168.121.127> (0, b'ansible-tmp-1669856332.5616784-16360-75421636728884=/home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884\n', b'')
Using module file /home/john/projects/cloud/python3_venv/lib/python3.10/site-packages/ansible/modules/file.py
<192.168.121.127> PUT /root/.ansible/tmp/ansible-local-156391xcnlln2/tmpanhevels TO /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/AnsiballZ_file.py
<192.168.121.127> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' /root/.ansible/tmp/ansible-local-156391xcnlln2/tmpanhevels '[192.168.121.127]:/home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/AnsiballZ_file.py'
<192.168.121.127> (0, b'', b'')
<192.168.121.127> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.127> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.127 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/ /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.127> (0, b'', b'')
<192.168.121.127> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.127> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' -tt 192.168.121.127 '/bin/sh -c '"'"'/usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.127> (1, b'\r\n{"path": "/home/vagrant/containers_cache/redis", "failed": true, "msg": "chown failed: [Errno 1] Operation not permitted: b\'/home/vagrant/containers_cache/redis\'", "exception": "  File \\"/tmp/ansible_ansible.builtin.file_payload_vrnp_8b0/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\\", line 833, in set_owner_if_different\\n    os.lchown(b_path, uid, -1)\\n", "uid": 1000, "gid": 1000, "owner": "vagrant", "group": "vagrant", "mode": "0755", "state": "directory", "size": 4096, "invocation": {"module_args": {"path": "/home/vagrant/containers_cache/redis", "owner": "104", "group": "104", "mode": 448, "state": "directory", "recurse": false, "force": false, "follow": true, "modification_time_format": "%Y%m%d%H%M.%S", "access_time_format": "%Y%m%d%H%M.%S", "unsafe_writes": false, "_original_basename": null, "_diff_peek": null, "src": null, "modification_time": null, "access_time": null, "seuser": null, "serole": null, "selevel": null, "setype": null, "attributes": null}}}\r\n', b'')
<192.168.121.127> Failed to connect to the host via ssh: 
<192.168.121.127> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.127> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.127 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.121.127> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_ansible.builtin.file_payload_vrnp_8b0/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py", line 833, in set_owner_if_different
    os.lchown(b_path, uid, -1)
failed: [instance] (item=/home/vagrant/containers_cache/redis) => {
    "ansible_loop_var": "item",
    "changed": false,
    "gid": 1000,
    "group": "vagrant",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "follow": true,
            "force": false,
            "group": "104",
            "mode": 448,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": "104",
            "path": "/home/vagrant/containers_cache/redis",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": false
        }
    },
    "item": "/home/vagrant/containers_cache/redis",
    "mode": "0755",
    "msg": "chown failed: [Errno 1] Operation not permitted: b'/home/vagrant/containers_cache/redis'",
    "owner": "vagrant",
    "path": "/home/vagrant/containers_cache/redis",
    "size": 4096,
    "state": "directory",
    "uid": 1000
}
```
> Example playbook:

You playbook works for folder creation?

**Comment by Igortorrente** [comment]
The real issue is the `group` parameter. Without it, everything works. but why?

**Comment by grzs** [comment]
The main thing I spotted in your output is that you don't use podman unshare, or any become plugin. Here is your command (passed to ssh):
```
 '/bin/sh -c '"'"'/usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1669856332.5616784-16360-75421636728884/AnsiballZ_file.py && sleep 0'"'"''
```
and here is mine:
```
'/bin/sh -c '"'"'podman unshare /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-aiqdsaabzlomlnutglwixeugrvgaebsg ; /usr/bin/python3 /home/grzs/.ansible/tmp/ansible-tmp-1669876748.67737-8659-5919824389005/AnsiballZ_file.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

**Comment by grzs** [comment]
if you want to check out exactly what's going on, you can run your playbook like this:
```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -i hosts podman_test.yml -vvv
```
After that in your vagrant box cd into /home/vagrant/.ansible/tmp where you can find a directory with AnsiballZ_file.py per task. You can simply execute this file or extract with this command:
```
python3 AnsiballZ_file.py explode
```
after that, you can find the scripts in debug_dir.
The chown related stuff are in debug_dir/ansible/module_utils/basic.py
According to your output, the execution failed here:
line 833, in set_owner_if_different ; os.lchown(b_path, uid, -1)

**Comment by grzs** [comment]
Please checkout the repo/reinstall this collection, because I fixed the default value. After that you have to specify become directives only at the specific task. And no become_user is needed if you connect with vagrant.
Here is an example:
```yaml
  - name: chown a directory with unshare
    become_method: containers.podman.podman_unshare
    become: yes
    ansible.builtin.file:
      state: directory
      path: "{{ test_dir }}"
      owner: 104
      group: 104
```
You can paste your task yaml here as well.

**Comment by Igortorrente** [comment]
I will be busy for some days, so I will not be able to test the newer version. But as soon as I have time I will test and post the results

**Comment by grzs** [comment]
Thanks for letting us know, no problem.

Igortorrente ***@***.***> ezt írta (időpont: 2022. dec. 2.,
P, 0:31):

**Comment by Igortorrente** [comment]
Thanks for the patience. I followed the instructions in the readme and cloned the repo in `/home/root/.ansible/collections/ansible_collections/containers/podman`. But it still failing when I add the group paramter

Current commit:

``` git
/home/root/.ansible/collections/ansible_collections/containers/podman $ git show
commit e39439831f29f5307f463e5572f916c127117772 (HEAD -> master, origin/master, origin/HEAD)
Author: János Gerzson <gerzsonj@gmail.com>
Date:   Wed Nov 30 22:08:18 2022 +0100
 
    [FIX] Issue #529: become plugin podman_unshare become_user default (#530)
```

The tasks:

```yaml
- name: chown a file with unshare
  become_method: containers.podman.podman_unshare
  become_user: "{{ ansible_user_id }}"
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ cache_dir }}/foo"
    owner: 1000
    group: 1001
    mode: 0744
```

Command `(root) molecule -vvv test`

``` yaml
[...]

TASK [roles/playbook_vars/ : chown a file with unshare] ************************
task path: /home/igor/projects/cloud/Caedrium-Playbooks/roles/playbook_vars/tasks/main.yml:2
<192.168.121.148> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.148> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.148 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
<192.168.121.148> (0, b'/home/vagrant\n', b'')
<192.168.121.148> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.148> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.148 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440 `" && echo ansible-tmp-1670375861.4643784-14284-199439145960440="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440 `" ) && sleep 0'"'"''
<192.168.121.148> (0, b'ansible-tmp-1670375861.4643784-14284-199439145960440=/home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440\n', b'')
Using module file /home/igor/projects/cloud/python3_venv/lib/python3.10/site-packages/ansible/modules/file.py
<192.168.121.148> PUT /root/.ansible/tmp/ansible-local-14255j9c8j911/tmpo3dypbsv TO /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440/AnsiballZ_file.py
<192.168.121.148> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' /root/.ansible/tmp/ansible-local-14255j9c8j911/tmpo3dypbsv '[192.168.121.148]:/home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440/AnsiballZ_file.py'
<192.168.121.148> (0, b'', b'')
<192.168.121.148> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.148> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.148 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440/ /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.148> (0, b'', b'')
<192.168.121.148> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.148> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' -tt 192.168.121.148 '/bin/sh -c '"'"'/usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.148> (1, b'\r\n{"path": "/home/vagrant/containers_cache", "failed": true, "msg": "chgrp failed", "exception": "  File \\"/tmp/ansible_ansible.builtin.file_payload_pk3blrmb/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\\", line 874, in set_group_if_different\\n    os.lchown(b_path, -1, gid)\\n", "uid": 1000, "gid": 1000, "owner": "vagrant", "group": "vagrant", "mode": "0755", "state": "directory", "size": 4096, "invocation": {"module_args": {"state": "directory", "path": "/home/vagrant/containers_cache/foo", "owner": "1000", "group": "1001", "mode": 484, "recurse": false, "force": false, "follow": true, "modification_time_format": "%Y%m%d%H%M.%S", "access_time_format": "%Y%m%d%H%M.%S", "unsafe_writes": false, "_original_basename": null, "_diff_peek": null, "src": null, "modification_time": null, "access_time": null, "seuser": null, "serole": null, "selevel": null, "setype": null, "attributes": null}}}\r\n', b'')
<192.168.121.148> Failed to connect to the host via ssh: 
<192.168.121.148> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.148> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.148 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1670375861.4643784-14284-199439145960440/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.121.148> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_ansible.builtin.file_payload_pk3blrmb/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py", line 874, in set_group_if_different
    os.lchown(b_path, -1, gid)
fatal: [instance]: FAILED! => {
    "changed": false,
    "gid": 1000,
    "group": "vagrant",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "follow": true,
            "force": false,
            "group": "1001",
            "mode": 484,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": "1000",
            "path": "/home/vagrant/containers_cache/foo",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": false
        }
    },
    "mode": "0755",
    "msg": "chgrp failed",
    "owner": "vagrant",
    "path": "/home/vagrant/containers_cache",
    "size": 4096,
    "state": "directory",
    "uid": 1000
}

[...]
```

**Comment by Igortorrente** [comment]
Thanks for the patience. I followed the instructions in the readme and cloned the repo in `/home/root/.ansible/collections/ansible_collections/containers/podman`. But it still failing when I add the group paramter

Current commit:

``` git
/home/root/.ansible/collections/ansible_collections/containers/podman $ git show
commit e39439831f29f5307f463e5572f916c127117772 (HEAD -> master, origin/master, origin/HEAD)
Author: János Gerzson <gerzsonj@gmail.com>
Date:   Wed Nov 30 22:08:18 2022 +0100
 
    [FIX] Issue #529: become plugin podman_unshare become_user default (#530)
```

The tasks:

```yaml
- name: chown a file with unshare
  become_method: containers.podman.podman_unshare
  become_user: "{{ ansible_user_id }}"
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ cache_dir }}/foo"
    owner: 1000
    group: 1001
    mode: 0744
```

Command `(root) molecule -vvv test`

``` yaml
[...]

TASK [roles/playbook_vars/ : chown a file with unshare] ************************
task path: /home/igor/projects/cloud/Caedrium-Playbooks/roles/playbook_vars/tasks/main.yml:16
<192.168.121.162> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.162> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.162 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
<192.168.121.162> (0, b'/home/vagrant\n', b'')
<192.168.121.162> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.162> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.162 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716 `" && echo ansible-tmp-1670377691.9429414-25119-220384939700716="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716 `" ) && sleep 0'"'"''
<192.168.121.162> (0, b'ansible-tmp-1670377691.9429414-25119-220384939700716=/home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716\n', b'')
Using module file /home/igor/projects/cloud/python3_venv/lib/python3.10/site-packages/ansible/modules/file.py
<192.168.121.162> PUT /root/.ansible/tmp/ansible-local-249902bmp46no/tmpya_w60el TO /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716/AnsiballZ_file.py
<192.168.121.162> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' /root/.ansible/tmp/ansible-local-249902bmp46no/tmpya_w60el '[192.168.121.162]:/home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716/AnsiballZ_file.py'
<192.168.121.162> (0, b'', b'')
<192.168.121.162> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.162> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.162 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716/ /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.162> (0, b'', b'')
<192.168.121.162> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.162> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' -tt 192.168.121.162 '/bin/sh -c '"'"'/usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.162> (1, b'\r\n{"path": "/home/vagrant/containers_cache", "failed": true, "msg": "chgrp failed", "exception": "  File \\"/tmp/ansible_ansible.builtin.file_payload_6suyk275/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\\", line 874, in set_group_if_different\\n    os.lchown(b_path, -1, gid)\\n", "uid": 1000, "gid": 1000, "owner": "vagrant", "group": "vagrant", "mode": "0755", "state": "directory", "size": 4096, "invocation": {"module_args": {"state": "directory", "path": "/home/vagrant/containers_cache/foo", "owner": "1000", "group": "1001", "mode": 484, "recurse": false, "force": false, "follow": true, "modification_time_format": "%Y%m%d%H%M.%S", "access_time_format": "%Y%m%d%H%M.%S", "unsafe_writes": false, "_original_basename": null, "_diff_peek": null, "src": null, "modification_time": null, "access_time": null, "seuser": null, "serole": null, "selevel": null, "setype": null, "attributes": null}}}\r\n', b'')
<192.168.121.162> Failed to connect to the host via ssh: 
<192.168.121.162> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.162> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.162 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1670377691.9429414-25119-220384939700716/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.121.162> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_ansible.builtin.file_payload_6suyk275/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py", line 874, in set_group_if_different
    os.lchown(b_path, -1, gid)
fatal: [instance]: FAILED! => {
    "changed": false,
    "gid": 1000,
    "group": "vagrant",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "follow": true,
            "force": false,
            "group": "1001",
            "mode": 484,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": "1000",
            "path": "/home/vagrant/containers_cache/foo",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": false
        }
    },
    "mode": "0755",
    "msg": "chgrp failed",
    "owner": "vagrant",
    "path": "/home/vagrant/containers_cache",
    "size": 4096,
    "state": "directory",
    "uid": 1000
}


[...]
```

And with

``` yaml
- name: chown a directory with unshare
  become_method: containers.podman.podman_unshare
  become: yes
  ansible.builtin.file:
    state: directory
    path: "{{ cache_dir }}/foo"
    owner: 104
    group: 104
```

The output

```
[...]

TASK [roles/playbook_vars/ : chown a directory with unshare] *******************
task path: /home/igor/projects/cloud/Caedrium-Playbooks/roles/playbook_vars/tasks/main.yml:16
<192.168.121.37> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.37 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
<192.168.121.37> (0, b'/home/vagrant\n', b'')
<192.168.121.37> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.37 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123 `" && echo ansible-tmp-1670377887.343758-26709-856541479123="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123 `" ) && sleep 0'"'"''
<192.168.121.37> (0, b'ansible-tmp-1670377887.343758-26709-856541479123=/home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123\n', b'')
Using module file /home/igor/projects/cloud/python3_venv/lib/python3.10/site-packages/ansible/modules/file.py
<192.168.121.37> PUT /root/.ansible/tmp/ansible-local-26612e3ftoppc/tmp8k0r_jnd TO /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123/AnsiballZ_file.py
<192.168.121.37> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' /root/.ansible/tmp/ansible-local-26612e3ftoppc/tmp8k0r_jnd '[192.168.121.37]:/home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123/AnsiballZ_file.py'
<192.168.121.37> (0, b'', b'')
<192.168.121.37> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.37 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123/ /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123/AnsiballZ_file.py && sleep 0'"'"''
<192.168.121.37> (0, b'', b'')
<192.168.121.37> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' -tt 192.168.121.37 '/bin/sh -c '"'"'sudo -iu root -- podman unshare /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rwfbalojisqkhbffgspacflprzkxduvd ; /usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123/AnsiballZ_file.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<192.168.121.37> (125, b'Error: please use unshare with rootless\r\n', b'')
<192.168.121.37> Failed to connect to the host via ssh: 
<192.168.121.37> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.cache/molecule/Caedrium-Playbooks/default/.vagrant/machines/instance/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'ControlPath="/root/.ansible/cp/%h-%p-%r"' 192.168.121.37 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1670377887.343758-26709-856541479123/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.121.37> (0, b'', b'')
fatal: [instance]: FAILED! => {
    "changed": false,
    "module_stderr": "",
    "module_stdout": "Error: please use unshare with rootless\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 125
}

[...]

```

**Comment by grzs** [comment]
Hi again,
it seems that when you applied become_user, no become plugin was involved, which is weird. You can check this by comparing your outputs' fifth 'SSH: EXEC' lines.
(There are 6 of such steps: 1. checking connection with echo; 2. creating temp dir; 3. copying "compiled" script AnsiballZ_file.py to temp dir; 4. 'chmod u+x' the latter file; 5. running the compiled file; 6. cleanup).

The other strange thing is that when become plugin is applied (2nd run) it runs with 'sudo root', which is impossible with the recent changes (https://github.com/containers/ansible-podman-collections/blob/e39439831f29f5307f463e5572f916c127117772/plugins/become/podman_unshare.py#L133).

Therefore I assume that something's wrong with your setup. Maybe the previous version of this collection is present somewhere on your controller machine. You can check the location by running `ansible-doc -t become containers.podman.podman_unshare`. You can also create an ansible.cfg like this:
```
[defaults]
become_plugins=~/.ansible/plugins/become:/usr/share/ansible/plugins/become
```

**Comment by Igortorrente** [comment]
Fair enough. I also think it's something with my setup.

I will close the issue and if I manage to solve the issue I will post here.

Thank you @grzs!

**Comment by grzs** [comment]
ok, I hope you can use the plugin somehow
